################################################################################
# COMPREHENSIVE PARASITE PREVALENCE AND RISK FACTOR ANALYSIS
# Project: Zoonotic Endoparasites in Free-Roaming Cats (NYC)
# Manuscript: PONE-D-26-00846 (PLOS ONE, 2026)
# Authors:    Nguyen, Gurtowski, Chen, Rosen, Kafle
# Contact:    kafle@rowan.edu
#
# OVERVIEW:
# This script processes the de-identified dataset
# ('cats_parasite_dataset.csv') and reproduces every numeric result reported
# in the manuscript:
#   1. Prevalence with 95% Wilson CIs (Table 1).
#   2. Risk-factor analysis (Fisher's Exact Tests) for infection presence.
#   3. Infection intensity analysis (Negative Binomial GLM / Mann-Whitney U).
#   4. CSV outputs for Tables 1 and 2.
#
# INPUT:  cats_parasite_dataset.csv  (in same folder as this script)
# OUTPUT: output/tables/Table1.csv, output/tables/Table2.csv
#
# Method note: Egg counts in this study were generated by the Wisconsin
# double-centrifugation flotation technique on a weighed fecal aliquot,
# yielding a quantitative eggs-per-gram (EPG) measure.
################################################################################

# ==============================================================================
# 1. SETUP
# ==============================================================================
required_packages <- c("MASS", "dplyr", "broom")

for (pkg in required_packages) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org")
    library(pkg, character.only = TRUE)
  }
}

# Resolve script folder (works in RStudio and command line)
this_dir <- tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),
                     error = function(e) getwd())
if (this_dir == "" || is.null(this_dir)) this_dir <- getwd()

output_tables  <- file.path(this_dir, "output", "tables")
if (!dir.exists(output_tables)) dir.create(output_tables, recursive = TRUE)

# ==============================================================================
# 2. DATA LOADING AND PREPARATION
# ==============================================================================
df <- read.csv(
  file.path(this_dir, "cats_parasite_dataset.csv"),
  na.strings = c("", "NA", " ")
)

# ----- Binary infection outcomes -----
df$rounds_pos <- ifelse(!is.na(df$toxocara_epg) & df$toxocara_epg > 0, 1, 0)
df$hooks_pos  <- ifelse(!is.na(df$ancylostoma_epg) & df$ancylostoma_epg > 0, 1, 0)
df$coccid_pos <- ifelse(!is.na(df$coccidia_epg)   & df$coccidia_epg   > 0, 1, 0)

df$any_parasite <- ifelse(df$rounds_pos == 1 | df$hooks_pos == 1 | df$coccid_pos == 1, 1, 0)

df$coinfection_count       <- df$rounds_pos + df$hooks_pos + df$coccid_pos
df$is_coinfected           <- ifelse(df$coinfection_count >= 2, 1, 0)
df$toxo_ancy_coinfection   <- ifelse(df$rounds_pos == 1 & df$hooks_pos == 1, 1, 0)

df$giardia_pos <- ifelse(df$giardia_antigen        == "Y", 1, 0)
df$crypto_pos  <- ifelse(df$cryptosporidium_antigen == "Y", 1, 0)
df$toxo_Ab_pos <- ifelse(df$toxoplasma_serology    == "Y", 1, 0)

# ----- Demographic factors -----
df$Age_Group <- NA
df$Age_Group[df$age_class %in% c("K", "J")] <- "Young"
df$Age_Group[df$age_class == "A"]           <- "Adult"

df$Sex_Clean <- NA
df$Sex_Clean[df$sex == "M"] <- "Male"
df$Sex_Clean[df$sex == "F"] <- "Female"

df$Age_Group <- factor(df$Age_Group, levels = c("Adult", "Young"))
df$Sex_Clean <- factor(df$Sex_Clean, levels = c("Female", "Male"))

# ==============================================================================
# 3. PREVALENCE (TABLE 1)
# ==============================================================================
n_float   <- 87
n_antigen <- 43
n_sero    <- 45

calc_prev_row <- function(name, method, positives, n_total) {
  test <- suppressWarnings(prop.test(positives, n_total, conf.level = 0.95, correct = FALSE))
  data.frame(
    Parasites          = name,
    Diagnostic_Method  = method,
    Pos_Total          = paste0(positives, " / ", n_total),
    Prevalence_Pct     = round((positives/n_total)*100, 1),
    CI_95              = paste0(round(test$conf.int[1]*100, 1), " - ",
                                round(test$conf.int[2]*100, 1))
  )
}

table1 <- rbind(
  calc_prev_row("Toxocara spp.",        "Fecal Flotation",    sum(df$rounds_pos, na.rm = TRUE), n_float),
  calc_prev_row("Ancylostoma spp.",     "Fecal Flotation",    sum(df$hooks_pos,  na.rm = TRUE), n_float),
  calc_prev_row("Trichuris spp.",       "Fecal Flotation",    0,                                n_float),
  calc_prev_row("Coccidia",             "Fecal Flotation",    sum(df$coccid_pos, na.rm = TRUE), n_float),
  calc_prev_row("Giardia spp.",         "Coproantigen ELISA", sum(df$giardia_pos, na.rm = TRUE), n_antigen),
  calc_prev_row("Cryptosporidium spp.", "Coproantigen ELISA", sum(df$crypto_pos,  na.rm = TRUE), n_antigen),
  calc_prev_row("Toxoplasma gondii",    "Serology (MAT)",     sum(df$toxo_Ab_pos, na.rm = TRUE), n_sero)
)

cat("\n--- TABLE 1: PREVALENCE ---\n")
print(table1)

cat("\n--- COINFECTION TEXT STATS ---\n")
print(calc_prev_row("Coinfection (2+)",       "Flotation", sum(df$is_coinfected, na.rm = TRUE),         n_float))
print(calc_prev_row("Toxocara + Ancylostoma", "Flotation", sum(df$toxo_ancy_coinfection, na.rm = TRUE), n_float))

# ==============================================================================
# 4. RISK FACTORS AND INTENSITY (TABLE 2)
# ==============================================================================
get_risk_stats <- function(data, group_col, outcome_col, target_group) {
  sub <- data[!is.na(data[[group_col]]) & !is.na(data[[outcome_col]]), ]
  tbl <- table(sub[[group_col]], sub[[outcome_col]])
  n_target <- sum(sub[[group_col]] == target_group)
  n_pos    <- sum(sub[[group_col]] == target_group & sub[[outcome_col]] == 1)
  prev_pct <- ifelse(n_target > 0, round((n_pos / n_target) * 100, 1), 0)

  if (nrow(tbl) < 2 || ncol(tbl) < 2) return(list(prev = prev_pct, or = NA, ci = "NC", p = 1))
  ft <- fisher.test(tbl)
  list(prev = prev_pct,
       or   = round(ft$estimate, 1),
       ci   = paste0(round(ft$conf.int[1], 1), "-", round(ft$conf.int[2], 1)),
       p    = ft$p.value)
}

get_int_stats <- function(data, group_col, epg_col, target_group, test_method = "mw") {
  sub_pos <- data[!is.na(data[[group_col]]) & !is.na(data[[epg_col]]) & data[[epg_col]] > 0, ]
  vals <- sub_pos[[epg_col]][sub_pos[[group_col]] == target_group]
  median_val <- ifelse(length(vals) > 0, round(median(vals), 1), 0)

  p_val <- NA
  if (test_method == "nb") {
    f <- as.formula(paste(epg_col, "~", group_col))
    try({
      model <- glm.nb(f, data = data)
      p_val <- summary(model)$coefficients[2, 4]
    }, silent = TRUE)
  } else {
    f <- as.formula(paste(epg_col, "~", group_col))
    try({
      test <- wilcox.test(f, data = sub_pos)
      p_val <- test$p.value
    }, silent = TRUE)
  }
  list(median = median_val, p = p_val)
}

# Toxocara
tox_age_risk    <- get_risk_stats(df, "Age_Group", "rounds_pos", "Young")
tox_sex_risk    <- get_risk_stats(df, "Sex_Clean", "rounds_pos", "Male")
tox_age_ref     <- get_risk_stats(df, "Age_Group", "rounds_pos", "Adult")
tox_sex_ref     <- get_risk_stats(df, "Sex_Clean", "rounds_pos", "Female")
tox_age_int     <- get_int_stats(df,  "Age_Group", "toxocara_epg", "Young", "nb")
tox_sex_int     <- get_int_stats(df,  "Sex_Clean", "toxocara_epg", "Male",  "nb")
tox_age_int_ref <- get_int_stats(df,  "Age_Group", "toxocara_epg", "Adult", "nb")
tox_sex_int_ref <- get_int_stats(df,  "Sex_Clean", "toxocara_epg", "Female","nb")

# Ancylostoma
anc_age_risk    <- get_risk_stats(df, "Age_Group", "hooks_pos", "Young")
anc_sex_risk    <- get_risk_stats(df, "Sex_Clean", "hooks_pos", "Male")
anc_age_ref     <- get_risk_stats(df, "Age_Group", "hooks_pos", "Adult")
anc_sex_ref     <- get_risk_stats(df, "Sex_Clean", "hooks_pos", "Female")
anc_age_int     <- get_int_stats(df,  "Age_Group", "ancylostoma_epg", "Young", "mw")
anc_sex_int     <- get_int_stats(df,  "Sex_Clean", "ancylostoma_epg", "Male",  "mw")
anc_age_int_ref <- get_int_stats(df,  "Age_Group", "ancylostoma_epg", "Adult", "mw")
anc_sex_int_ref <- get_int_stats(df,  "Sex_Clean", "ancylostoma_epg", "Female","mw")

fmt_p <- function(p) {
  if (is.na(p)) return("-")
  if (p < 0.001) return("<0.001")
  format(round(p, 3), nsmall = 3)
}

table2 <- data.frame(
  Demographic_Group = c("Age", "Young (<1 yr)", "Adult (>=1 yr)", "Sex", "Male", "Female"),
  N = c("",
        sum(df$Age_Group == "Young", na.rm = TRUE),
        sum(df$Age_Group == "Adult", na.rm = TRUE),
        "",
        sum(df$Sex_Clean == "Male", na.rm = TRUE),
        sum(df$Sex_Clean == "Female", na.rm = TRUE)),
  Tox_Prev_OR_CI = c("",
    paste0(tox_age_risk$prev, "% (", tox_age_risk$or, "; ", tox_age_risk$ci, ")"),
    paste0(tox_age_ref$prev,  "% (Reference)"),
    "",
    paste0(tox_sex_risk$prev, "% (", tox_sex_risk$or, "; ", tox_sex_risk$ci, ")"),
    paste0(tox_sex_ref$prev,  "% (Reference)")),
  Tox_Med_EPG_P = c("",
    paste0(tox_age_int$median, " (", fmt_p(tox_age_int$p), ")"),
    paste0(tox_age_int_ref$median),
    "",
    paste0(tox_sex_int$median, " (", fmt_p(tox_sex_int$p), ")"),
    paste0(tox_sex_int_ref$median)),
  Anc_Prev_OR_CI = c("",
    paste0(anc_age_risk$prev, "% (", anc_age_risk$or, "; ", anc_age_risk$ci, ")"),
    paste0(anc_age_ref$prev,  "% (Reference)"),
    "",
    paste0(anc_sex_risk$prev, "% (", anc_sex_risk$or, "; ", anc_sex_risk$ci, ")"),
    paste0(anc_sex_ref$prev,  "% (Reference)")),
  Anc_Med_EPG_P = c("",
    paste0(anc_age_int$median, " (", fmt_p(anc_age_int$p), ")"),
    paste0(anc_age_int_ref$median),
    "",
    paste0(anc_sex_int$median, " (", fmt_p(anc_sex_int$p), ")"),
    paste0(anc_sex_int_ref$median))
)

cat("\n--- TABLE 2: DEMOGRAPHICS AND BURDEN ---\n")
print(table2)

# ==============================================================================
# 5. EXPORT TO CSV
# ==============================================================================
write.csv(table1, file = file.path(output_tables, "Table1.csv"), row.names = FALSE)
write.csv(table2, file = file.path(output_tables, "Table2.csv"), row.names = FALSE)
cat("\nTables written to:", output_tables, "\n")
